build:
	protoc --proto_path=proto:. --go_out=plugins=micro:out/ proto/consignment/consignment.proto
	protoc --proto_path=proto:. --go_out=plugins=micro:out/ proto/vessel/vessel.proto
	protoc --proto_path=proto:. --go_out=plugins=micro:out/ proto/user/user.proto
	protoc --proto_path=proto:. --go_out=plugins=micro:out/ proto/log/log.proto
